### ISSUE TITLE
debugger still breaking after I turn off the breakpoint

### ISSUE THREAD

**Issue by steveja42** [rubyide/vscode-ruby#44] opened 2016-08-09 03:12 UTC
### Your environment
- `vscode-ruby` version: 0.5.2 
- Ruby version:   2.2
- VS Code version: 1.4
- Operating System: windows 10 
- Hardware (optional): 

Make sure you have `ruby`, `ruby-debug-ide` and `ruby-debug-basex19` installed before submitting your issue -- thank you !
### Expected behavior

the debugger doesn't stop on the line after removing the breakpoint
### Actual behavior

the debugger does stop on the line
### Steps to reproduce the problem

click to the left of a line in main.rb to set a breakpoint, line 12 below for example
debug the local ruby script,
after the debugger stops at the line, click to the left of the line to remove the breakpoint 
continue the script and then the debugger still stops as if there were a breakpoint

main.rb

file = File.read("test.txt")
words = {}
file.split.each {|aword|

```
count = words[aword]
if count
    count = count + 1
else
    count = 1 
end

words = words.merge aword=>count
```

}
words.each { |key, value|
        puts "The word #{key} accours #{value} times"

}

**Comment by jljse** [comment] 2016-08-20 10:25
I have same trouble (vscode-ruby=0.5.2  ruby=2.3.1  VSCode=1.4  windows10)
This problem seems to happen only for breakponts which : 
 - already exist when debugging start.
 - break on it when removed.
Thank you.

**Comment by rebornix** [comment] 2016-08-21 13:53
The problem is that breakpoint removal after debugger gets launched doesn't work.

@chriskacerguis want to give this a try?

**Comment by Dashue** [comment] 2017-03-09 17:00
Bump

**Comment by wingrunr21** [comment] 2018-04-03 18:43
Closing for issue cleanup. Apologies if this is still an issue. We are working to improve the core extension experience.

**Closed by wingrunr21** 2018-04-03 18:43 UTC
Labels: bug

**Comment by thomthom** [comment] 2018-04-03 19:03
Yes, this is still an issue. Does this mean this won't be looked into?

What does "core extension experience" mean?

**Comment by wingrunr21** [comment] 2018-04-03 19:08
It means creating a roadmap to get the extension in a good place. I am planning on looking at the debugger for this. Closing this issue was part of the cleanup process.

See [here](https://github.com/rubyide/vscode-ruby/issues/239#issuecomment-378358853) for an explanation

**Comment by gisrao** [comment] 2019-01-25 09:31
Hello when I debug on VSCode that   Debugger error: Client: Error: connect ECONNREFUSED 127.0.0.1:7000
