### ISSUE TITLE
Linters quit working

### ISSUE THREAD

**Issue by michael-bowen-sp** [rubyide/vscode-ruby#508] opened 2019-07-15 18:21 UTC
### Your environment

- `vscode-ruby` version: 0.24.1
- Ruby version: 2.5.5
- Ruby version manager (if any): rvm
- VS Code version: 1.36.1
- Operating System: OSX
- Using language server? (eg `useLanguageServer` is true?) 

### Expected behavior
linters work
### Actual behavior
linters quit working

Rubocop and Reek quit working in the past week. I uninstalled the Ruby extension and reinstalled and reek worked again but then magically quit working the next time I opened the folder in VSCode.

Here is my settings.json

```
{
    "window.zoomLevel": 2,
    "[python]": {
        "editor.tabSize": 4
    },
    "[go]": {
        "editor.tabSize": 4
    },
    "editor.formatOnSave": true,
    "editor.formatOnSaveTimeout": 5000,
    "editor.tabSize": 2,
    "files.insertFinalNewline": true,
    "files.trimTrailingWhitespace": true,
    "editor.minimap.enabled": false,
    "editor.rulers": [
        80
    ],
    // Basic settings: turn linter(s) on
    "ruby.lint": {
        "reek": true
    }
}
```

**Comment by henrytseng** [comment] 2019-07-26 16:26
Is it possible the linter output when you add multiple linters is overwritten?  I saw the output blink when multiple linters were on (rubocop/reek)

**Comment by wingrunr21** [comment] 2019-07-28 14:52
You aren't using the language server so you aren't using environment detection. You thus have to start VSCode with the correct environment variables set (eg us `code .` from the command line).

**Comment by michael-bowen-sp** [comment] 2019-07-31 15:13
@wingrunr21 Where in the docs is that specified?

**Comment by henrytseng** [comment] 2019-07-31 15:17
Looks like it only happens when multiple linters are running.  I am kicking off with `code .`

```{
    "window.zoomLevel": 2,
    "[python]": {
        "editor.tabSize": 4
    },
    "[go]": {
        "editor.tabSize": 4
    },
    "editor.formatOnSave": true,
    "editor.formatOnSaveTimeout": 5000,
    "editor.tabSize": 2,
    "files.insertFinalNewline": true,
    "files.trimTrailingWhitespace": true,
    "editor.minimap.enabled": false,
    "editor.rulers": [
        80
    ],
    // Basic settings: turn linter(s) on
    "ruby.lint": {
        "reek": true,
        "rubocop": true
    }
}
```

**Comment by michael-bowen-sp** [comment] 2019-08-02 21:21
@henrytseng I got reek and rubocop to work in a fresh directory with its own workspace, but when I try to use the same workspace settings in my work project I get this error:
`rubocop failed with code=7`

**Comment by michael-bowen-sp** [comment] 2019-08-02 21:31
@henrytseng So I deleted my Gemfile and all of a sudden it works....

**Comment by wingrunr21** [comment] 2019-08-18 19:13
I am closing this issue as it appears the issue is more or less resolved. In addition, I've done a holistic revamp of the documentation over the past few weeks that should (hopefully) be much clearer.

**Closed by wingrunr21** 2019-08-18 19:13 UTC

**Comment by michael-bowen-sp** [comment] 2019-08-19 15:11
Link to documentation changes or the PR?

**Comment by wingrunr21** [comment] 2019-08-19 15:12
@michael-bowen-sp `master`
