### ISSUE TITLE
Problems running auto complete

### ISSUE THREAD

**Issue by SirWindfield** [rubyide/vscode-ruby#100] opened 2016-12-07 12:52 UTC
### Your environment

- `vscode-ruby` version: 
- Ruby version: ruby 2.3.1p112 (2016-04-26 revision 54768) [x64-mingw32]
- VS Code version: 1.7.2
- Operating System: Windows 10

### Expected behavior
Hitting `Ctrl+Space` after ``[1,2,3].e` should bring up auto complete.

### Actual behavior
Bothing happens, just the basic word suggestion appears.

### Steps to reproduce the problem
Nothing special here....

I have no idea why this is happening. I used the offical ruby windows installer and the devkit.

**Comment by anvarich** [comment] 2016-12-08 14:56
Same here. Autocomplete not working.

**Comment by alicevixie** [comment] 2016-12-10 07:43
Same here. And yes, I did gem install rcodetools

**Comment by HookyQR** [comment] 2016-12-10 08:51
There may be a path issue. Try setting `"ruby.rctComplete.commandPath"` to the location of the `rct-complete` executable in your users settings. `rct-complete` also requires a path to your `ruby` executable if it is not found in a directory in your `%PATH%` environment variable.

**Comment by anvarich** [comment] 2016-12-10 10:30
@HookyQR set path in user settings, autocomplete not working. But rubocop work all this time.

**Comment by anvarich** [comment] 2016-12-13 14:06
@HookyQR @rebornix guys any update?

**Comment by pkeuter** [comment] 2016-12-15 22:09
Pressing CTRL+Space with developer tools open shows this in the console:
> shell.ts:541 An unknown error occurred. Please consult the log for more details.
Maybe this helps finding out what's wrong

**Comment by SirWindfield** [comment] 2016-12-15 23:20
I can't access my windows PC till after Christmas. Will post the log then

**Comment by behind-design** [comment] 2016-12-16 00:24
In my case what happens is that I get autocompletion as long as I'm in the "global" scope kinda speaking. But if I'm inside a `block` (i.e `[1, 2, 3].map do |item|..`), autocompletion doesn't work.

**Comment by behind-design** [comment] 2016-12-16 00:47
This issue, #72 is related to this, so keep an eye on it.

**Comment by pkeuter** [comment] 2016-12-16 06:18
@behind-design not sure if it's related as you say, because for some people (me, for instance) it doesn't work at all. Does the console show the same output?

**Comment by wojtek23** [comment] 2017-04-25 18:46
Same here, I also have rcodetools installed
- ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-linux] via RVM
- vscode 1.11.2

do you use RVM? Maybe that's the case?

**Comment by dmlemos** [comment] 2017-08-22 19:40
I get these in the developer console when trying to auto-complete.

```
lintBuilders[l] is not a constructor: TypeError: lintBuilders[l] is not a constructor
    at Linter._runLinters (.../.vscode/extensions/rebornix.ruby-0.15.0/out/lint/lib/linter.js:102:28)
    at Linter.run (.../.vscode/extensions/rebornix.ruby-0.15.0/out/lint/lib/linter.js:28:21)
    at LintCollection.run (.../.vscode/extensions/rebornix.ruby-0.15.0/out/lint/lintCollection.js:21:40)
    at executeLinting (.../.vscode/extensions/rebornix.ruby-0.15.0/out/ruby.js:107:17)
    at e.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:55038)
    at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:56829)
    at t.$acceptModelChanged (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:346011)
    at t.e.handle (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:308751)
    at s (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:188848)
    at h (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:189503)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
e.onUnexpectedError @ shell.ts:423
(anonymous) @ shell.ts:383
e.onUnexpectedError @ errors.ts:119
o @ errors.ts:139
t.onUnexpectedExtHostError @ mainThreadErrors.ts:13
e.handle @ abstractThreadService.ts:34
s @ ipcRemoteCom.ts:275
f @ ipcRemoteCom.ts:231
_combinedTickCallback @ internal/process/next_tick.js:67
_tickCallback @ internal/process/next_tick.js:98
shell.ts:423 An unknown error occurred. Please consult the log for more details.
e.onUnexpectedError @ shell.ts:423
(anonymous) @ shell.ts:383
e.onUnexpectedExternalError @ errors.ts:125
t.onUnexpectedExternalError @ errors.ts:147
v @ winjs.base.raw.js:1209
enter @ winjs.base.raw.js:901
_run @ winjs.base.raw.js:1068
_error @ winjs.base.raw.js:1041
v @ winjs.base.raw.js:1209
enter @ winjs.base.raw.js:901
_run @ winjs.base.raw.js:1068
_error @ winjs.base.raw.js:1041
(anonymous) @ async.ts:360
done @ winjs.base.raw.js:1378
v @ winjs.base.raw.js:1224
enter @ winjs.base.raw.js:901
_run @ winjs.base.raw.js:1068
_error @ winjs.base.raw.js:1041
e.resolveErr @ ipcRemoteCom.ts:111
f @ ipcRemoteCom.ts:203
_combinedTickCallback @ internal/process/next_tick.js:67
_tickCallback @ internal/process/next_tick.js:98
```

**Comment by castwide** [comment] 2018-02-01 05:08
https://github.com/rubyide/vscode-ruby/pull/248 should resolve this issue.

**Comment by yanivps** [comment] 2018-02-09 10:25
Can someone guide please how to make this work if I am working on vscode installed on windows and my ruby is installed on WSL (Bash on Windows) ?
I think the problem is that extention is trying to run all commands in the context of the Windows OS and not the Linux, but ruby is not installed on windows.
I tried to workaround this with adding a folder to windows PATH and add .bat file per gem I have (including ruby, rct-complete and solargraph) and the content of the bat file was this:
@echo off
bash -c '~/.rbenv/shims/solargraph %*'
but unfortunately it didn't work.

**Comment by castwide** [comment] 2018-02-11 22:50
I've experimented with WSL, but so far I haven't been able to execute Ruby on WSL from a Windows process. If anyone else has had success with it, I'd love to hear about it.

**Comment by yanivps** [comment] 2018-02-22 14:31
The only solution I can suggest you for now is to install Xming which enables you to run UI applications on WSL. Then you can install vscode on your Ubuntu on Windows and run it (use this thread for instructions)
For this to succeed, you will have to update Windows 10 to 17063 build which is not official yet so you will have to enable Windows insider program and update

I chose not to perform this update through Windows insider program and wait for the next official Windows 10 update which should include this build (Per microsoft it should come in April)

**Comment by wingrunr21** [comment] 2018-04-03 18:47
Closing for issue cleanup. Apologies if this is still an issue. We are working to improve the core extension experience.

**Closed by wingrunr21** 2018-04-03 18:47 UTC
Labels: autocomplete, bug
