### ISSUE TITLE
Strange highlighting of def...end blocks

### ISSUE THREAD

**Issue by TheTharin** [rubyide/vscode-ruby#322] opened 2018-04-09 10:22 UTC
Hello! I'm new to VSCode and I haven't really found means to fix this issue (maybe it is fixable through configuration, but I just can't find it). The thing is - when you have a general expression that involves if/unless in its code without necessary 'end' statement (ex: return value if value == 1), it still connects that 'if/unless' statement to the 'end' statement that comes after it, which is wrong and confusing. I find highlighting of block start and block end a great feature and I really hope there is a way to do it like it's done in rubymine.

- `vscode-ruby` version:  0.17.0
- Ruby version: 2.4.1
- VS Code version: 1.21.1
- Operating System: OS X
- Hardware (optional): 

### Expected behavior
http://prntscr.com/j2tf3q

### Actual behavior
http://prntscr.com/j2tf9t

### Steps to reproduce the problem
Open any *.rb file. Type this:
`def something`
  `return true if 1 == 1`
`end`
Then click on 'end'

**Comment by wingrunr21** [comment] 2018-04-09 12:45
Dupe of #282

**Closed by wingrunr21** 2018-04-09 12:45 UTC
