### ISSUE TITLE
Intellisense not working

### ISSUE THREAD

**Issue by sepehr500** [rubyide/vscode-ruby#120] opened 2017-02-14 01:50 UTC
Your environment

vscode-ruby version:
Ruby version: ruby 2.3.1
VS Code version: 1.9
Operating System: Ubuntu 16.04
Expected behavior

Hitting Ctrl+Space after ``[1,2,3].e` should bring up Intellisense

Actual behavior

Nothing happens, just the basic word suggestion appears.

Steps to reproduce the problem

 ``[1,2,3].e` should bring up Intellisense, but only brings up standard auto complete

**Comment by wagenet** [comment] 2017-02-15 17:26
I'm having this issue as well.

**Comment by raldred** [comment] 2017-02-16 17:07
Same on OSX.
I have rcodetools installed.

VScode 1.9.1 (f9d0c687ff2ea7aabd85fb9a43129117c0ecf519)
Ruby Ext: 0.10.4
Ruby 2.4.0

**Comment by HookyQR** [comment] 2017-02-17 00:44
`rcodetools` is somewhat iffy. Install methods can be an issue too. Have you installed it with `bundler`? Are you using a ruby version manager?

**Comment by sepehr500** [comment] 2017-02-17 15:27
How do I find where my rctComplete in installed?

**Comment by raldred** [comment] 2017-02-17 16:28
@sepehr500 `which rctComplete`

@HookyQR I use RVM, ruby 2.4.0 is my --default ruby and definitely has `rcodetools` installed
I installed it using the Integrated Terminal

**Comment by ivcosla** [comment] 2017-03-24 11:11
@raldred I found that  rct-complete asked me for a ruby interpreter I didn't have (/usr/local/bin/ruby18). I just created a symbolic link between my interpreter and the one that rct-complete asked me for:

`sudo ln -s /usr/bin/ruby /usr/local/bin/ruby18 `

I think it would be better to have the interpreter for ruby18, im just linking my ruby2.3, but my intellisense is working now. By the way, I can't tell if it is fully working or not.

**Comment by jgroeneveld** [comment] 2017-06-01 07:32
i have the same issue. sometimes it works kinda outside of functions but as soon as the file contains code that is project related (so non standard lib constants) i have a uninitialized constant error. do i need to configure the workspace or something?

**Comment by rvong** [comment] 2017-10-25 20:24
Still doesn't work.

**Comment by raldred** [comment] 2017-10-26 11:52
I have moved to using solargraph
https://github.com/castwide/vscode-solargraph

**Comment by alexishida** [comment] 2017-11-24 12:44
+1

**Comment by basicBrogrammer** [comment] 2017-12-09 02:37
![image](https://user-images.githubusercontent.com/6913826/33791792-220c0fc6-dc4f-11e7-92e5-5a7a0662dd76.png)
 

This is what happens for me.

**Comment by AndrewKiri** [comment] 2017-12-28 20:49
+1  
* macOS High Sierra 10.13.2
* VSCode 1.19.1
* Ruby version 2.4.1

**Comment by castwide** [comment] 2018-02-01 05:06
https://github.com/rubyide/vscode-ruby/pull/248 should resolve this issue. It adds the Solargraph extension that @raldred mentioned as a dependency.

**Comment by yanivps** [comment] 2018-02-09 10:22
Can someone guide please how to make this work if I am working on vscode installed on windows and my ruby is installed on WSL (Bash on Windows) ?
I think the problem is that extention is trying to run all commands in the context of the Windows OS and not the Linux. I tried to workaround this with adding a folder to windows PATH and add .bat file per gem I have (including ruby, rct-complete and solargraph) and the content of the bat file was this:
`@echo off  
bash -c '~/.rbenv/shims/solargraph %*' 
`
but unfortunately it didn't work.

**Comment by nascimento** [comment] 2018-02-22 13:47
+1

**Comment by castwide** [comment] 2018-02-22 13:56
I commented on the WSL issue here: https://github.com/rubyide/vscode-ruby/issues/100

**Comment by yanivps** [comment] 2018-02-22 14:31
The only solution I can suggest you for now is to install [Xming](https://sourceforge.net/projects/xming/) which enables you to run UI applications on WSL. Then you can install vscode on your Ubuntu on Windows and run it (use this [thread](https://github.com/Microsoft/WSL/issues/2760#issuecomment-352967045) for instructions)
For this to succeed, you will have to update Windows 10 to 17063 build which is not official yet so you will have to [enable Windows insider program](https://www.windowscentral.com/how-join-windows-insider-program) and update

I chose not to perform this update through Windows insider program and wait for the next official Windows 10 update which should include this build (Per microsoft it should come in April)

**Comment by wingrunr21** [comment] 2018-04-03 18:45
Closing for issue cleanup. Apologies if this is still an issue. We are working to improve the core extension experience.

**Closed** 2018-04-03 18:47 UTC
Labels: autocomplete, question
