### ISSUE TITLE
Shorthand if should not highlight end

### ISSUE THREAD

**Issue by rmcbarreto** [rubyide/vscode-ruby#587] opened 2020-02-07 15:16 UTC
### Your environment

- `vscode-ruby` version: 0.26.0
- Ruby version: 1.9.3
- VS Code version: 1.41.1
- Operating System: Windows 10

### Expected behaviour
When selecting a shorthand if, it should not highlight the next end.

### Actual behaviour

![image](https://user-images.githubusercontent.com/16502550/74040850-755e1200-49bc-11ea-8bde-78ce34773aa7.png)

### Steps to reproduce the problem
Open any *.rb file. Type this:

    def test
        (0..5).each do |item|
            next if item == 3
            if item == 3 or item == 4
                puts "Hi"
            end
        end
    end

Select the shorthand if and it will highlight the end of the cycle.

**Comment by wingrunr21** [comment] 2020-02-12 18:03
Thanks for the report. Are you using the language server?

**Comment by wingrunr21** [comment] 2020-02-23 16:39
I am unable to reproduce this while using the language server. Closing for now.

**Closed by wingrunr21** 2020-02-23 16:39 UTC
Labels: need-more-info
