### ISSUE TITLE
I can't see the end line of code

### ISSUE THREAD

**Issue by nwoow** [rubyide/vscode-ruby#368] opened 2018-07-15 18:19 UTC
I am using mac I am using the latest version of visual code. I have installed vscode-ruby But I can't see the end of my code blocks.

I have a very complex if else block and I can't see the end of those blocks. Is this a bug because someone on stackoverflow told me it is working for him. 

I want to find a way to see end and starting code block. Is there any settings I am missing.
<img width="1440" alt="error" src="https://user-images.githubusercontent.com/3254550/42736900-6dd28a50-888b-11e8-821b-8c732741e1b8.png">

**Comment by nwoow** [comment] 2018-07-15 18:32
check the screen shot

**Comment by nwoow** [comment] 2018-07-15 18:33
I uninstalled visual code reinstall restart everything but no luck. Sometimes I was able to see when restarted but now nothing is happening.

**Comment by wingrunr21** [comment] 2018-07-15 18:36
If you are referring to the `respond_to` blocks, it looks like they are missing the `end` keyword (as the line numbers don't show a hidden line). If you `cat` the file do you see the `end`s?

**Comment by nwoow** [comment] 2018-07-15 18:42
It is not detecting the simple def end block not highlighter When I removed all project folder it showed for few minutes but after that it is gone. What is the issue.

**Comment by nwoow** [comment] 2018-07-15 18:53
I found the solution I don't  know why my visual code of ruby is in LF mode I changed it to CRLF and it is working. Is there any way to choose CLRF for all proejct

**Comment by nicbet** [comment] 2018-07-30 17:50
I can confirm. Had the same issue (def/end highlights not working). @nwoow points at the correct solution: changing `LF` to `CRLF` re-enabled these highlights.

**Comment by wingrunr21** [comment] 2018-07-30 18:01
Ok. Any more information you all can provide? I use LF line endings and do not have this issue. Other extensions?

**Comment by nwoow** [comment] 2018-07-30 18:07
@nicbet changing from LF to CRLF it works but I need to do it for each file but I don't know how to fix it.

**Comment by wingrunr21** [comment] 2018-07-30 18:14
Look for the user config setting “files.eol”

**Comment by nwoow** [comment] 2018-07-30 18:17
In my setting it is   "files.eol": "\n" why am I getting this problem in my mac and my ubntu. Is there any fix to this problem.

**Comment by wingrunr21** [comment] 2018-07-30 21:50
I don't know why this problem is happening. I cannot reproduce it.

`files.eol` is how you change your default line endings. You said `CRLF` fixes the issue for you.

**Comment by nicbet** [comment] 2018-07-31 14:44
Did some more testing on my Mac - after I changed EOL _once_ from `LF` to `CRLF` highlighting works regardless of the EOL setting. I.e., setting back to `LF`, or opening another file which is either `LF`, or `CRLF` the highlighting will work. Almost looks like it needs at kick at the tire to start working, but then will work regardless of setting...

**Comment by wingrunr21** [comment] 2018-07-31 14:58
Out of curiosity, if you change the language on the file to just text, do the `end`s show back up? I'm trying to figure out if this is the extension or VSCode being wonky

**Comment by nicbet** [comment] 2018-07-31 15:17
Changed the language from `Ruby` to `Plain Text`, and then back to `Ruby` -> highlights start working.

**Comment by wingrunr21** [comment] 2018-07-31 22:12
hmm, interesting. Do you have any VSCode settings local to the repository or workspace?

**Comment by nwoow** [comment] 2018-08-01 01:33
I have tried everything but I can see highlighting of end line when I change lf to crlf or I change file from ruby to text adn then ruby. But when I go to other file and open again it stop working. I don't know if it is a bug or setting same thing happening on my ubuntu and on my mac.

**Comment by nwoow** [comment] 2018-08-01 10:55
Problem here is when I open file and do some activity only then I see highlighter. Is this normal

**Comment by wingrunr21** [comment] 2018-08-03 14:16
Ok, are you both seeing issues with the `end` disappearing or issues with the `def-end` highlighting? The original post was about `end`s not being visible. The highlighting issue is known and will be resolved when #366 is merged and the new language server is available.

If this issue is specifically about highlighting then I'd like to close this. If the issue is about `end`s vanishing I'd like to keep it open.

**Comment by wingrunr21** [comment] 2019-02-24 20:52
Closing due to inactivity

**Closed by wingrunr21** 2019-02-24 20:52 UTC
