### ISSUE TITLE
Typing `do` and pressing enter should automatically insert `end`

### ISSUE THREAD

**Issue by ecbrodie** [rubyide/vscode-ruby#213] opened 2017-10-06 19:20 UTC
### Your environment

- `vscode-ruby` version: 0.15.0
- Ruby version: 2.4.1
- VS Code version: 1.16.1
- Operating System: MacOS 10.12.6

### Steps to reproduce the problem

Create a block by typing a statement that ends with `do` and press enter.

### Expected behavior

The newline is given one additional level of indentation. Another line that just has the`end` keyword is automatically inserted on a line below the cursor.

### Actual behavior

The line with `end` is not automatically inserted, so I am forced to tediously type this in. The new line is indented, however.

Please PR this into this extension. This really keeps me from being able to use VSCode as an IDE for my Ruby code. This is a feature that's available in other modern IDEs for Ruby, such as RubyMine and Atom.

### Notes

I wonder if there are elements of this issue related to #210.

**Comment by papa-whisky** [comment] 2017-10-06 23:33
It'd be nice if this functionality was included in this extension, but in the meantime you can use: https://github.com/kaiwood/vscode-endwise

**Comment by ecbrodie** [comment] 2017-10-07 03:04
@papa-whisky thanks for that suggestion, I'm going to install that one right now.

I wonder if it is worth making a PR to add a note about this _temporary_ workaround until this is added to vscode-ruby.

**Comment by aoozdemir** [comment] 2017-12-02 16:30
Also, as in Atom, `dop` or some alternative should create a block with block parameter.

**Comment by rebornix** [comment] 2018-02-01 03:30
Sorry for replying this issue so late. @ecbrodie it's a nice feature to have in vscode-ruby, so PR welcome!

@aoozdemir I suppose what you described is code snippet, which you can add to your personal snippet file in VSCode.

**Comment by ecbrodie** [comment] 2018-02-01 03:58
I rarely use VSCode anymore, so I have little incentive to submit a PR
unless that situation changes. I do highly encourage this package's core
contributors to take on implementing this, though. The do...end blocks are
quite a core and frequently used language feature of Ruby, so lacking this
functionality will severely hinder this package's adoption rate.

**Comment by kaiwood** [comment] 2018-02-01 15:02
@rebornix If wanted, I can prepare a PR and port the functionality over to this extension (Wasn‘t aware there is an open issue here, this one was opened shortly after our last conversation). 

But I need to find the cause of a performance bug first, after the last update of *this* extension I started noticing a slowdown when pressing enter and now received an issue from another user (https://github.com/kaiwood/vscode-endwise/issues/7) - disabling this one solves it, but is not really a viable solution :)

Anyways, question: Should this feature have a setting to disable it? Enabled or disabled by default?

**Comment by aoozdemir** [comment] 2018-02-01 15:09
@rebornix I can't believe I've missed that idea. Thank you 👍

**Comment by wingrunr21** [comment] 2018-04-03 18:50
Closing for issue cleanup. Apologies if this is still an issue. We are working to improve the core extension experience.

**Closed by wingrunr21** 2018-04-03 18:50 UTC
Labels: feature-request
