### ISSUE TITLE
Debugger error: Client: Error: read ECONNRESET

### ISSUE THREAD

**Issue by alexsoares** [rubyide/vscode-ruby#117] opened 2017-02-01 17:05 UTC
### Your environment

- `vscode-ruby` version: 0.10.3
- Ruby version: 1.9.3
- VS Code version: 0.10.3
- Operating System: Linux Mint 17

Make sure you have `ruby`, `ruby-debug-ide` and `ruby-debug-basex19` installed before submitting your issue -- thank you !

### Expected behavior
I would like debug a run rails server.

### Actual behavior
Show error: Debugger error: Client: Error: read ECONNRESET in vscode console, and in my rails terminal show:  ERROR bad Request-Line `start'
### Steps to reproduce the problem
Just apply this configuration and try to start debug session with this options:
        {
            "name": "Listen for rdebug-ide",
            "type": "Ruby",
            "request": "attach",
            "cwd": "${workspaceRoot}",
            "remoteHost": "172.23.24.97",
            "remotePort": "3000",
            "remoteWorkspaceRoot": "${workspaceRoot}"
        }

Alexandre Soares

**Comment by fzzr-** [comment] 2017-02-28 11:02
Same behaviour on macOS `10.11.6 (15G1217)`
Ruby: `2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin15]`
Error: `Debugger error: Client: Error: read ECONNRESET`

I think it happens for small fast programs and the debugger does not have time to connect because the program has already finished & terminated.

**Comment by Simas1** [comment] 2017-03-24 07:57
I have the same issue, with small code.
It solves the problem if I add sleep(1) at the end :)

**Comment by rebornix** [comment] 2017-04-17 18:00
@fzzr- @Simas1 do you mind providing an example which breaks in this case? I can't reproduce on my local machine.

**Comment by mrsteveheyes** [comment] 2017-04-18 11:47
@rebornix I have the same issue too. How best can I provide an example? A public git repo with or something?

**Comment by fzzr-** [comment] 2017-04-22 13:52
@mrsteveheyes Mb. on CI?

**Comment by jakauppila** [comment] 2017-12-28 16:18
I am having the same issue.

## Your environment
- vscode-ruby version: 0.15.0
- Ruby version: 2.4.1p111
- VS Code version: 1.19.1
- Operating System: Windows 10

Utilizing the following launch config:

```
{
  "name": "Debug Current Local File",
  "type": "Ruby",
  "request": "launch",
  "cwd": "${workspaceRoot}",
  "pathToRDebugIDE": "C:/Ruby24-x64/bin/rdebug-ide.bat",
  "program": "${file}"
}
```

And the following example:

```ruby
require 'chef/win32/security'
Chef::ReservedNames::Win32::Security.add_account_right('test', 'SeAuditPrivilege')
value = Chef::ReservedNames::Win32::Security.get_account_right('test')
puts value
```
It occasionally works, but I usually get the the error `Debugger error: Client: Error: read ECONNRESET`

**Comment by wingrunr21** [comment] 2018-04-03 18:46
Closing for issue cleanup. Apologies if this is still an issue. We are working to improve the core extension experience.

**Closed** 2018-04-03 18:46 UTC
Labels: need-more-info

**Comment by SevlaMare** [comment] 2020-09-05 18:51
> Closing for issue cleanup. Apologies if this is still an issue. We are working to improve the core extension experience.

Was getting the same error, with a similar setup, in some way, the problem was the file .vscode/settings.json, so I just delete it and all is working fine now.

The files were like:
launch.json
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Debug Local File",
      "type": "Ruby",
      "request": "launch",
      "cwd": "${workspaceRoot}",
      "program": "${file}",
    }
  ]
}
```

settings.json
```
{
  "key": "ctrl+shift+t",
  "command": "workbench.action.terminal.sendSequence",
  "args": { "text": "node '${file}'\u000D" }
}
```
