### ISSUE TITLE
Symbol strings (ex. :abc) via "Remote - SSH" are not correctly highlighted

### ISSUE THREAD

**Issue by danglduy** [rubyide/vscode-ruby#483] opened 2019-05-12 13:52 UTC
### Your environment

- `vscode-ruby` version: 0.22.3
- Ruby version: 2.6.3
- Ruby version manager (if any): rbenv
- VS Code version: 1.34.10-insider
- Operating System: Windows
- Using language server? Solargraph
- Using via "Remote - SSH" remote environment _([Link](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh))_

### Expected behavior
Symbol strings syntax is correctly highlighted
### Actual behavior
Symbol strings syntax is incorrectly highlighted

In the picture below `:exception` should be highlighted
![image](https://user-images.githubusercontent.com/38782010/57583136-aa096f80-74f7-11e9-9be2-c14d0353659d.png)

**Comment by connorshea** [comment] 2019-05-12 21:20
I assume this is the same problem as https://github.com/microsoft/vscode-remote-release/issues/153

**Comment by danglduy** [comment] 2019-05-13 11:20
I think these are not the same problems. Ruby symbols are correctly highlighted without any language servers anyway.

**Comment by minkir014** [comment] 2019-05-13 13:03
Have you tried that on an ordinary vs code?

**Comment by danglduy** [comment] 2019-05-13 13:27
@minkir014 "Remote - SSH" extension does only work on VS Code Insider I'm afraid.

**Comment by wingrunr21** [comment] 2019-05-13 14:51
hi @danglduy 

Can you use the `Developer: Inspect TM Scopes` tool to tell me what scopes are being matched for the `with: :exception` part of that code?

The `with:` should be matching the grammar with a scope of `constant.language.symbol.hashkey.ruby` and `:exception` should be `constant.language.symbole.ruby`.

**Comment by danglduy** [comment] 2019-05-13 15:58
@wingrunr21 I inspected `with:` and `:exception`
![image](https://user-images.githubusercontent.com/38782010/57635969-764f4800-75d2-11e9-9103-74aeb280004b.png)
![image](https://user-images.githubusercontent.com/38782010/57636006-86ffbe00-75d2-11e9-9ddb-861d52816fd6.png)

**Comment by wingrunr21** [comment] 2019-05-13 16:00
Ok. What theme are you using? The Ruby grammar is correctly matching the TM scopes but it appears your theme does not have support.

**Comment by danglduy** [comment] 2019-05-13 16:02
@wingrunr21 I am using the default theme.

**Comment by wingrunr21** [comment] 2019-05-13 16:03
Which is what? `Dark+`?

**Comment by danglduy** [comment] 2019-05-13 16:36
Yes it’s Dark+

**Comment by wingrunr21** [comment] 2019-05-14 12:16
interesting. I also use Dark+ and I get those keywords highlighted in blue. Do you get highlighting with a different theme?

**Comment by danglduy** [comment] 2019-05-14 12:29
@wingrunr Have you tried using in “Remote SSH” environment? I get highlighted normally in local environment.

**Comment by wingrunr21** [comment] 2019-05-14 12:55
No but that's what I'm trying to determine what the problem is. Does another theme give you correct highlighting?

The Remote SSH environment isn't stable yet and this extension doesn't explicitly support it. Theming is a core VSCode function as well. The grammar is supplying and matching a TM Scope but the theme doesn't have a matching style.

**Comment by OmriSama** [comment] 2019-07-16 23:30
Following

**Comment by OmriSama** [comment] 2019-07-18 17:17
Here's the difference between correctly working TM scope and a not correctly working one:

**CORRECT**
![image](https://user-images.githubusercontent.com/10534779/61477887-2fb8f980-a945-11e9-856e-9eedc23c5ec7.png)

**INCORRECT**
![image](https://user-images.githubusercontent.com/10534779/61477913-3d6e7f00-a945-11e9-9d7d-5c3b836a21da.png)

Issue is in `constant.language` vs `constant.other.symbol`

**Comment by minkir014** [comment] 2019-07-18 17:28
How have you displayed this in vscode insiders??? I mean what is displayed in the images.

**Comment by OmriSama** [comment] 2019-07-18 19:35
> 
> 
> How have you displayed this in vscode insiders??? I mean what is displayed in the images.

I opened the same directory in two windows, one was local VSCode and another one was Remote SSH.

**Comment by connorshea** [comment] 2019-07-18 19:41
There's a command in the command palette called "Inspect TM Scopes", I think that's what they're asking for.

**Comment by wingrunr21** [comment] 2019-07-18 20:27
That's what it is. I'm digging into Remote environments after I fix the current issue with `tree-sitter`. I haven't yet researched why VSCode is assigning different TextMate scopes between the two environments.

**Comment by OmriSama** [comment] 2019-07-27 21:59
Any updates on this?

**Comment by wingrunr21** [comment] 2019-11-19 19:50
This has been resolved in `v0.26.0`

**Closed** 2019-11-19 19:50 UTC

**Comment by OmriSama** [comment] 2019-11-19 22:25
@wingrunr21 thank you so much! This has been sorely lacking in my Ruby experience :)
