### ISSUE TITLE
Lint problems still appear after file is deleted

### ISSUE THREAD

**Issue by garyking** [rubyide/vscode-ruby#324] opened 2018-04-09 18:15 UTC
Create a file, with lint errors, like:

```ruby
def test(a, b, c)
  return 'test'
end
```

Wait until errors appear. I'm using Rubocop. Then delete the file. The errors remain. 

Instead, the errors should disappear after the file is deleted, per other linters like ESLint.

**Comment by wingrunr21** [comment] 2018-04-09 18:51
Agreed. Closing as a dupe of #238

**Closed by wingrunr21** 2018-04-09 18:51 UTC
