### ISSUE TITLE
Yard syntax highlighting incorrect for @ sign and when numbers are encountered in a line

### ISSUE THREAD

**Issue by noraj** [rubyide/vscode-ruby#560] opened 2019-11-19 12:47 UTC
### Your environment

```
Version: 1.40.1
Commit: 8795a9889db74563ddd43eb0a897a2384129a619
Date: 2019-11-15T22:58:14.270Z
Electron: 6.1.1
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 4.19.84-1-lts
```

Settings:

```json
{
    "editor.tokenColorCustomizations": {
        "textMateRules": [
            {
                "scope": [
                    "comment.line.keyword.punctuation.yard.ruby",
                    "comment.line.keyword.yard.ruby",
                    "comment.line.parameter.yard.ruby",
                    "comment.line.type.yard.ruby",
                    "comment.line.string.yard.ruby",
                ],
                "settings": {
                    "foreground": "#7f848eff"
                },
            },
            {
                "scope": "comment.line.type.yard.ruby",
                "settings": {
                    "foreground": "#4ec9b0"
                },
            },
            {
                "scope": "comment.line.parameter.yard.ruby",
                "settings": {
                    "foreground": "#9cdcfe"
                },
            },
            {
                "scope": "comment.line.punctuation.yard.ruby",
                "settings": {
                    "foreground": "#7f848eff"
                },
            },
            {
                "scope": "comment.line.keyword.yard.ruby",
                "settings": {
                    "foreground": "#49c982"
                },
            },
        ]
    }
}
```

### Actual behavior

The parsing of `"comment.line.keyword.yard.ruby"` seems broken.
For example the parsing seems to stop when a number is reached (eg. `:sha256`). Also I was wondering if it's by design that the `@` sign is not highlighted with the tag verb?

![image](https://user-images.githubusercontent.com/16578570/69147504-65781580-0ad2-11ea-8b30-e631fb9a766d.png)

**Comment by wingrunr21** [comment] 2019-11-19 12:52
Not by design, just the way the TextMate grammar is and it subsequently got here. Same with the number part.

Thanks for the report. Marking as a bug

**Comment by noraj** [comment] 2019-11-19 16:16
And also for URL in `@see` comments.

![image](https://user-images.githubusercontent.com/16578570/69164419-44beb880-0af0-11ea-94e2-d5636a2f24ec.png)

**Comment by wingrunr21** [comment] 2019-11-19 16:19
Great, thanks. Just looks like one of the capture groups has an incorrect selector for that part of the grammar

**Comment by graceful-potato** [comment] 2020-10-15 18:47
I took a look at yard rules and and noticed that regexps for params and options do not contain digits. And looks like `@see` tag is in the wrong rule. 
I can try to fix it.

**Comment by graceful-potato** [comment] 2020-10-18 13:59
And also I noticed that in this example
```ruby
# @option opts [Symbol] :mode Default value: +:strict+.
```
`option` and `:mode` has the same scope but these parts have slightly different meanings. @wingrunr21  what do you think if I add additional scope to the `:mode` part?

**Closed** 2020-10-30 12:32 UTC
Labels: bug
