### ISSUE TITLE
end doesn't un-indent

### ISSUE THREAD

**Issue by pharmmd-rich** [rubyide/vscode-ruby#99] opened 2016-12-05 17:16 UTC
### Your environment

macOS Sierra 10.12.1
VSCode version 1.7.2
Ruby plugin version 0.10.4

User settings:
```
{
    "workbench.editor.enablePreview": true,
    "explorer.openEditors.visible": 0,
    "editor.tabSize": 2,
    "editor.detectIndentation": false
}
```
### Expected behavior

`end` should auto un-indent properly after a `def`, `module`, `class`, etc.

### Actual behavior
`end` doesn't auto un-indent properly after a `def`, `module`, `class`, etc.

### Steps to reproduce the problem

open an rb file or create a new one and type:

`def foo` and push enter, then type `end`

**Comment by HookyQR** [comment] 2016-12-05 19:12
Hi @pharmmd-rich, this is a known issue unfortunately. We're aware of it and there isn't an easy workaround unfortunately.

**Comment by TheAustinSeven** [comment] 2017-01-28 18:07
I don't know if it helps at all, but the systemverilog extension has automatic end insertion/unindentation. I'm not familiar with how they implemented it, and I know that it is a much simpler language, but I thought that I would drop that here.
![expected behavior](http://g.recordit.co/slSoDknpI9.gif).
The system verilog extension can be found [here](https://github.com/mshr-h/vscode-systemverilog-support).

**Comment by thomthom** [comment] 2017-02-03 14:14
The recent 1.9 release mentioned improved support for indentation for language extensions: https://code.visualstudio.com/updates/v1_9#_indentation-rules-improvements

> #### Indentation rules improvements
> We polished our implementation of Indentation Rules, which Language extensions can leverage to determine the correct indentation level for a specific line. The indentation adjustments are usually triggered after users finish writing a line and press Enter.
>
> In addition, we implemented an experimental command Reindent Lines and you can use it to adjust the indentation of the whole file if the indentation rules are properly set.

Could these changes help this extension such that manually un-indenting every `end` isn't needed?

**Comment by pharmmd-rich** [comment] 2017-02-03 14:41
It does help to an extent.  Now, in Ruby, if you type 'end' and then push enter, end will properly de-indent itself.  I haven't tried the extension mentioned above, but it'd be nice if the Ruby extension would implement that functionality.

**Comment by rebornix** [comment] 2017-02-06 00:32
The indentation rules enhancement was implemented by me as well :) Right now as Code only supports indentation adjustments when you press enter, you can see the indentation adjusts properly, with or without this extension.

I'll keep working on the indentation improvement in Code and personally I'd like to bring in *auto indent*, in which case you don't need to rely on pressing Enter. As this extension already has a good indentation rules setting, we don't need to change anything here.

**Comment by StanBright** [comment] 2017-04-26 23:41
@rebornix hey mate, thanks for the great work!

Any ideas when the extended functionality regarding auto-indent could see some light :)?

**Comment by papa-whisky** [comment] 2017-07-12 01:39
@rebornix thanks for your work on the extension so far, I use it every day and it's a great help :)

Will the [changes to auto-indentation](https://code.visualstudio.com/updates/v1_14#_auto-indent-on-type-move-lines-and-paste) in the latest VS Code release help to resolve this issue? Looks promising...

**Comment by rebornix** [comment] 2017-07-12 02:23
Yes, that feature is particularly for this case. If you take a look at the gif in the release note of 1.14, you'll see that I use Ruby code as an example :)

**Comment by rebornix** [comment] 2017-07-12 02:24
Just set editor.autoIndent to true. Hope you guys like it

**Comment by papa-whisky** [comment] 2017-07-12 02:27
Oh, didn't realise it was off by default, haha. All working now. Great update, thanks @rebornix !

**Comment by aried3r** [comment] 2017-07-12 09:28
Awesome, @rebornix! I saw the `indentationRules` part of the release notes but I'm not entirely sure if I need to enable anything or if this extension needs these rules to work with pasting code? I tried but it doesn't seem to work right now.

My guess is we need to add the `indentationRules` for files like .rb and .html.erb etc?

**Comment by pharmmd-rich** [comment] 2017-07-12 14:32
@aried3r it works out of the box.  You just have to enable the setting.

**Comment by aried3r** [comment] 2017-07-12 20:12
@pharmmd-rich, I did enable it, sorry if that wasn't clear. Does indenting on pasting work for you, though? That's what I'm actually asking.

**Comment by pharmmd-rich** [comment] 2017-07-12 20:13
Pasting has been working great for me, way better than previously.  Are you having an issue?

**Comment by aried3r** [comment] 2017-07-12 20:21
Yeah, pasting ruby code still does not auto-indent, usually retaining all the whitespace of the first line in addition to the existing whitespace of the line. The remaining pasted lines retain the indentation of the source.

So the current workflow looks like this:
* Make a new line
* Paste
* Manually indent first line
* Mark remaining N-1 lines and indent them manually

Ideally I'd love to skip the last two, which I though was coming with VSCode 1.14

**Comment by wingrunr21** [comment] 2018-04-03 18:47
Closing for issue cleanup. Apologies if this is still an issue. We are working to improve the core extension experience.

**Closed by wingrunr21** 2018-04-03 18:47 UTC
Labels: feature-request
